stations = {
    'Tuas Link': set(['Tuas West Road']),
    'Tuas West Road': set(['Tuas Crescent', 'Tuas Link']),
    'Tuas Crescent': set(['Gul Circle', 'Tuas West Road']),
    'Gul Circle': set(['Joo Koon', 'Tuas Crescent']),
    'Joo Koon': set(['Pioneer', 'Gul Circle']),
    'Pioneer': set(['Joo Koon', 'Boon Lay']),
    'Boon Lay': set(['Lakeside', 'Pioneer']),
    'Lakeside': set(['Chinese Garden', 'Boon Lay']),
    'Chinese Garden': set(['Jurong East', 'Lakeside']),
    'Jurong East': set(['Clementi', 'Bukit Batok', 'Chinese Garden']),
    'Clementi': set(['Jurong East', 'Dover']),
    'Dover': set(['Clementi', 'Buona Vista']),
    'Buona Vista': set(['one-north', 'Holland Village', 'Dover', 'Commonwealth']),
    'Commonwealth': set(['Buona Vista', 'Queenstown']),
    'Queenstown': set(['Redhill', 'Commonwealth']),
    'Redhill': set(['Tiong Bahru', 'Queenstown']),
    'Tiong Bahru': set(['Outram Park', 'Redhill']),
    'Outram Park': set(['Tiong Bahru', 'Tanjong Pagar', 'Havelock', 'Maxwell', 'Chinatown', 'HarbourFront']),
    'Tanjong Pagar': set(['Raffles Place', 'Outram Park']),
    'Raffles Place': set(['City Hall', 'Tanjong Pagar', 'Marina Bay']),
    'City Hall': set(['Raffles Place', 'Bugis', 'Dhoby Ghaut']),
    'Bugis': set(['City Hall', 'Lavender', 'Rochor', 'Promenade']),
    'Lavender': set(['Bugis', 'Kallang']),
    'Kallang': set(['Lavender', 'Aljunied']),
    'Aljunied': set(['Kallang', 'Paya Lebar']),
    'Paya Lebar': set(['MacPherson', 'Dakota', 'Aljunied', 'Eunos']),
    'Eunos': set(['Kembangan', 'Paya Lebar']),
    'Kembangan': set(['Bedok', 'Eunos']),
    'Bedok': set(['Kembangan', 'Tanah Merah']),
    'Tanah Merah': set(['Bedok', 'Expo', 'Simei']),
    'Expo': set(['Tanah Merah', 'Changi Airport']),
    'Changi Airport': set(['Expo']),
    'Simei': set(['Tampines', 'Tanah Merah']),
    'Tampines': set(['Tampines East', 'Tampines West', 'Pasir Ris', 'Simei']),
    'Pasir Ris': set(['Tampines']),
    'Bukit Batok': set(['Jurong East', 'Bukit Gombak']),
    'Bukit Gombak': set(['Bukit Batok', 'Choa Chu Kang']),
    'Choa Chu Kang': set(['Bukit Gombak', 'Yew Tee', 'South View']),
    'Yew Tee': set(['Kranji', 'Choa Chu Kang']),
    'Kranji': set(['Yew Tee', 'Marsiling']),
    'Marsiling': set(['Kranji', 'Woodlands']),
    'Woodlands': set(['Woodlands North', 'Woodlands South', 'Marsiling', 'Admiralty']),
    'Admiralty': set(['Sembawang', 'Woodlands']),
    'Sembawang': set(['Canberra', 'Admiralty']),
    'Canberra': set(['Sembawang', 'Yishun']),
    'Yishun': set(['Canberra', 'Khatib']),
    'Khatib': set(['Yishun', 'Yio Chu Kang']),
    'Yio Chu Kang': set(['Ang Mo Kio', 'Khatib']),
    'Ang Mo Kio': set(['Bishan', 'Yio Chu Kang']),
    'Bishan': set(['Marymount', 'Lorong Chuan', 'Ang Mo Kio', 'Braddell']),
    'Braddell': set(['Bishan', 'Toa Payoh']),
    'Toa Payoh': set(['Novena', 'Braddell']),
    'Novena': set(['Newton', 'Toa Payoh']),
    'Newton': set(['Orchard', 'Novena', 'Stevens', 'Little India']),
    'Orchard': set(['Orchard Boulevard', 'Great World', 'Somerset', 'Newton']),
    'Somerset': set(['Dhoby Ghaut', 'Orchard']),
    'Dhoby Ghaut': set(['Somerset', 'City Hall', 'Clarke Quay', 'Little India', 'Bras Basah']),
    'Marina Bay': set(['Marina South Pier', 'Raffles Place', 'Gardens by the Bay', 'Shenton Way', 'Bayfront']),
    'Marina South Pier': set(['Marina Bay']),
    'South View': set(['Choa Chu Kang', 'Keat Hong']),
    'Keat Hong': set(['South View', 'Teck Whye']),
    'Teck Whye': set(['Keat Hong', 'Phoenix']),
    'Phoenix': set(['Bukit Panjang', 'Teck Whye']),
    'Bukit Panjang': set(['Cashew', 'Senja', 'Petir']),
    'Senja': set(['Jelapang', 'Bukit Panjang']),
    'Jelapang': set(['Segar', 'Senja']),
    'Segar': set(['Fajar', 'Jelapang']),
    'Fajar': set(['Bangkit', 'Segar']),
    'Bangkit': set(['Fajar', 'Pending']),
    'Pending': set(['Petir', 'Bangkit']),
    'Petir': set(['Bukit Panjang', 'Pending']),
    'Cashew': set(['Bukit Panjang', 'Hillview']),
    'Hillview': set(['Beauty World', 'Cashew']),
    'Beauty World': set(['Hillview', 'King Albert Park']),
    'King Albert Park': set(['Sixth Avenue', 'Beauty World']),
    'Sixth Avenue': set(['King Albert Park', 'Tan Kah Kee']),
    'Tah Kah Kee': set(['Botanic Gardens', 'Sixth Avenue']),
    'Botanic Gardens': set(['Caldecott', 'Farrer Road', 'Tah Kah Kee', 'Stevens']),
    'Stevens': set(['Napier', 'Caldecott', 'Newton', 'Botanic Gardens']),
    'Little India': set(['Rochor', 'Newton', 'Farrer Park', 'Dhoby Ghaut']),
    'Rochor': set(['Little Inidia', 'Bugis']),
    'Promenade': set(['Bugis', 'Bayfront', 'Nicoll Highway', 'Esplanade']),
    'Bayfront': set(['Promenade', 'Downtown', 'Marina Bay']),
    'Downtown': set(['Telok Ayer', 'Bayfront']),
    'Telok Ayer': set(['Chinatown', 'Downtown']),
    'Chinatown': set(['Fort Canning', 'Telok Ayer', 'Outram Park', 'Clarke Quay']),
    'Fort Canning': set(['Bencoolen', 'Chinatown']),
    'Bencoolen': set(['Jalan Besar', 'Fort Canning']),
    'Jalan Besar': set(['Bendemeer', 'Bencoolen']),
    'Bendemeer': set(['Geylang Bahru', 'Jalan Besar']),
    'Geylang Bahru': set(['Bendemeer', 'Mattar']),
    'Mattar': set(['Geylang Bahru', 'MacPherson']),
    'MacPherson': set(['Ubi', 'Mattar', 'Tai Seng', 'Paya Lebar']),
    'Ubi': set(['Kaki Bukit', 'MacPherson']),
    'Kaki Bukit': set(['Bedok North', 'Ubi']),
    'Bedok North': set(['Kaki Bukit', 'Bedok Reservoir']),
    'Bedok Reservoir': set(['Bedok North', 'Tampines West']), 
    'Tampines West': set(['Tampines', 'Bedok Reservoir']),
    'Tampines East': set(['Upper Changi', 'Tampines']),
    'HarbourFront': set(['Outram Park']),
    'Clarke Quay': set(['Dhoby Ghaut', 'Chinatown']),
    'Farrer Park': set(['Little India', 'Boon Keng']),
    'Boon Keng': set(['Potong Pasir', 'Farrer Park']),
    'Potong Pasir': set(['Woodleigh', 'Boon Keng']),
    'Woodleigh': set(['Potong Pasir', 'Serangoon']),
    'Serangoon': set(['Bartley', 'Lorong Chuan', 'Kovan', 'Woodleigh']),
    'Kovan': set(['Hougang', 'Serangoon']),
    'Hougang': set(['Buangkok', 'Kovan']),
    'Buangkok': set(['Sengkang', 'Hougang']),
    'Sengkang': set(['Buangkok', 'Punggol']),
    'Punggol': set(['Sengkang']),
    'Nicoll Highway': set(['Promenade', 'Stadium']),
    'Stadium': set(['Mountbatten', 'Nicoll Highway']),
    'Bras Basah': set(['Dhoby Ghaut', 'Esplanade']),
    'Esplanade': set(['Promenade', 'Bras Basah']),
    'Mountbatten': set(['Stadium', 'Dakota']),
    'Dakota': set(['Mountbatten', 'Paya Lebar']),
    'Tai Seng': set(['Bartley', 'MacPherson']),
    'Bartley': set(['Serangoon', 'Tai Seng']),
    'Lorong Chuan': set(['Serangoon', 'Bishan']),
    'Marymount': set(['Caldecott', 'Bishan']),
    'Caldecott': set(['Upper Thomson', 'Stevens', 'Marymount', 'Botanic Gardens']),
    'Farrer Road': set(['Holland Village', 'Botanic Gardens']),
    'Holland Village': set(['Buona Vista', 'Farrer Road']),
    'one-north': set(['Kent Ridge', 'Buona Vista']),
    'Kent-Ridge': set(['one-north', 'Haw Par Villa']),
    'How Par Villa': set(['Kent Ridge', 'Pasir Panjang']),
    'Pasir Panjang': set(['Labrador Park', 'How Par Villa']),
    'Labrador Park': set(['Telok Blangah', 'Pasir Panjang']),
    'Telok Blangah': set(['Harbour Front', 'Labrador Park']),
    'Gardens by the Bay': set(['Marina Bay']),
    'Shenton Way': set(['Maxwell', 'Marina Bay']),
    'Maxwell': set(['Outram Park', 'Shenton Way']),
    'Havelock': set(['Great World', 'Outram Park']),
    'Great World': set(['Orchard', 'Havelock']),
    'Orchard Boulevard': set(['Orchard', 'Napier']),
    'Napier': set(['Stevens', 'Orchard Boulevard']),
    'Upper Thomson': set(['Bright Hill', 'Caldecott']),
    'Bright Hill': set(['Upper Thomson', 'Mayflower']),
    'Lentor': set(['Mayflower', 'Springleaf']),
    'Springleaf': set(['Lentor', 'Woodlands South']),
    'Woodlands South': set(['Woodlands', 'Springleaf']),
    'Woodlands North': set(['Woodlands'])
    }
